// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD79p9yQ-HpkYxCM2Xfil0J5kYbuPjC1a4',
    appId: '1:615790560369:web:e6c8bc5317c5b4deca47d0',
    messagingSenderId: '615790560369',
    projectId: 'trima-fit-4c05a',
    authDomain: 'trima-fit-4c05a.firebaseapp.com',
    storageBucket: 'trima-fit-4c05a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcwbqwdcr5BD9TkUCrNbBJqA_e--iles',
    appId: '1:615790560369:android:b24e7528c32e58b4ca47d0',
    messagingSenderId: '615790560369',
    projectId: 'trima-fit-4c05a',
    storageBucket: 'trima-fit-4c05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkpFX0xgfYB_-Htt79YJW6t714VZxWjPI',
    appId: '1:615790560369:ios:2ee4cd093fe5ca61ca47d0',
    messagingSenderId: '615790560369',
    projectId: 'trima-fit-4c05a',
    storageBucket: 'trima-fit-4c05a.appspot.com',
    iosBundleId: 'com.example.trimafitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkpFX0xgfYB_-Htt79YJW6t714VZxWjPI',
    appId: '1:615790560369:ios:2ee4cd093fe5ca61ca47d0',
    messagingSenderId: '615790560369',
    projectId: 'trima-fit-4c05a',
    storageBucket: 'trima-fit-4c05a.appspot.com',
    iosBundleId: 'com.example.trimafitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD79p9yQ-HpkYxCM2Xfil0J5kYbuPjC1a4',
    appId: '1:615790560369:web:6700b7c0f778948eca47d0',
    messagingSenderId: '615790560369',
    projectId: 'trima-fit-4c05a',
    authDomain: 'trima-fit-4c05a.firebaseapp.com',
    storageBucket: 'trima-fit-4c05a.appspot.com',
  );
}
